name: Simple Go Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go version
      uses: actions/setup-go@v3
      with:
        go-version: '1.17.1'
    - run: go run helloworld.go
